version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2-browsers
    steps:
      - checkout
      - run:
          name: install chromedriver
          command: |
            wget https://chromedriver.storage.googleapis.com/94.0.4606.41/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            ./chromedriver
          background: true
#      - run: bundle install
#      - run:
#          name: Save test results
#          command: |
#            mkdir -p ~/cucumber
#            bundle exec cucumber --format junit --out ~/cucumber/junit.xml
#          when: always
#      - store_test_results:
#          path: ~/cucumber
#      - store_artifacts:
#          path: ~/cucumber
