version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Save test results
          command: |
            mkdir -p ~/cucumber
            bundle exec cucumber --format junit --out ~/cucumber/junit.xml
          when: always
      - store_test_results:
          path: ~/cucumber
      - store_artifacts:
          path: ~/cucumber
