version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run test
          command: |
            mkdir -p ~/cucumber
            bundle exec cucumber --format junit --out ~/cucumber/junit.xml
          when: always
      - store_test_results:
          path: ~/cucumber
      - store_artifacts:
          path: ~/cucumber
