version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.2
jobs:
  test:
    docker:
      - image: cimg/ruby:3.0.2-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
