name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - name: Prepare Selenium
      uses: nanasess/setup-chromedriver@master
    - name: Start XVFB
      env:
        user_email: ${{ secrets.USER_EMAIL }}
        user_password: ${{ secrets.USER_PASSWORD }}
        DISPLAY: :99
      run: |
        echo $USER_EMAIL
        echo $user_email
        google-chrome --version
        google-chrome --headless --no-sandbox --disable-dev-shm-usage
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & 
        bundle exec cucumber
