name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - name: Set up ChromeDrive
        uses: nanasess/setup-chromedriver@master

      - name: Run Cucumber
        env:
          user_email: ${{ secrets.USER_EMAIL }}
          user_password: ${{ secrets.USER_PASSWORD }}
          DISPLAY: :99
        run: |
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          bundle exec cucumber
