name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0.2']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Prepare Selenium
      uses: nanasess/setup-chromedriver@master
    - name: Start XVFB
      run: |
        google-chrome --version
        google-chrome --headless --no-sandbox --disable-dev-shm-usage
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & 
        bundle exec cucumber
      env:
        DISPLAY: :99
